### ISSUE TITLE
回复

### ISSUE THREAD

**Issue by AXFOX** [MEMZSONBILI/MEMZSONBILI.github.io#3]
个人观点，芯片研发生产的各环节算得上高新技术，谁控股已经不是很重要了，因为华为想在中国混的好就得“懂事”，(想起来前几年政企都爱买联想的电脑方便报单....最近貌似联想把ThinkPad价格压了压，*当然还是贵的要死*，美帝企业真不是白吹的。)，“华为消费者服务真的很傻逼好吗？”这句话我是真的不敢恭维，你本地的门店什么服务我不清楚，我们这边是挺不错的，打电话的话也是很省事，哦对了如果要说不满意，*ROOT权限*是的，就是这个让我很不舒服，当时还打电话问客服，然后最后解锁码是拿到了，具体的怎么说的我忘了，当时是给华为畅享5解锁准备 的，不过后来忘了这回事，现在也没解锁，解锁码也丢了。P7那什么鬼我不清楚，就我用过的几款是挺舒服的，另外关于魅族，**”假ROOT权限“**说的就是魅族了，关于魅族部分机型的假ROOT权限问题你可以去谷歌一下，总之当初在基安是没少看见人骂这个。另外，国家资助我在吃:滑稽 ，如果本地高中义务教育的住宿费什么报销的好处算是国家资助的话（反正是本地政府出钱的就是了）。麒麟是否外卖不关我事，就算哪天小米没芯片求华为了，华为不给导致小米玩完又如何，商业公司不赚钱还叫商业公司？要说买华为这回事，我买了，华为挣到钱自己芯片能继续造呗。哪怕有一天中国卖手机的就剩华为了，那我也不在乎（前提是别像他们预想的那样一家独大就垄断抬价。）**毕竟价格本来就贵，这我没法说啥，OV之前骁龙400系列旗舰机的事情我也没法说啥。**
总的来说，我希望中国别出现垄断现象，我个人使用高通的SOC说实话是很舒服了，MTK现在也不错，华为别把麒麟带死就行了，不然中国就确实没几个还能大规模搞移动设备芯片的公司/组织机构了，话说，最近听说紫光的芯片...

**Comment by Eden7Ba23** [comment]
额...你这写的有点长，我抓几个点回复吧。
1、P7问题。当时我记得P7宣传1080P屏幕，现在WayBackMachine也可以看见 https://web.archive.org/web/20140511225723/http://consumer.huawei.com/cn/mobile-phones/tech-specs/ascend-p7-cn.htm ，但是我手上的P7-L09在坏掉之前我曾经用它作AIDA64副屏，结果是720P的...至于LG变JDI，如前文所述，机器坏了，无从得知。
2、假ROOT。这是魅族16出现的问题，我也酷安了解了一波。应该就是root权限几乎没给什么权限之类的。
3、紫光？你说虎贲的9863系和T600系吗？
4、听说台积电被迫断货华为了。中芯国际的14nm现在跟上了 但是7nm...
5、华为的消费者服务傻逼问题...别问 问就是荣耀10换个电池真的...

目前就这么多。
