### ISSUE TITLE
站点错误

### ISSUE THREAD

**Issue by zaochih** [MEMZSONBILI/MEMZSONBILI.github.io#7]
~~突发奇想想逛逛你博客 就 全白屏 Booooooooooooooooooooooom了~~

**Comment by Eden7Ba23** [comment]
> ~突发奇想想逛逛你博客 就 全白屏 Booooooooooooooooooooooom了~

[已经修复，感谢提醒．](https://github.com/YunYouJun/hexo-theme-yun/discussions/103)
